"""Add VoterPhoto model"""
revision = '3abc9c15aad2'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authentication_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('authentication_sessions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('elections', 'remote_voting_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('elections', 'voting_flow_mode',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'full'"))
    op.alter_column('elections', 'enable_step_2',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'enable_step_3',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'enable_step_4',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'enable_step_5',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'show_voter_names_in_results',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_elections_election_id'), 'elections', ['election_id'], unique=True)
    op.create_index(op.f('ix_elections_secure_voting_token'), 'elections', ['secure_voting_token'], unique=False)
    op.create_index(op.f('ix_elections_secure_voting_token_hash'), 'elections', ['secure_voting_token_hash'], unique=False)
    op.create_foreign_key(None, 'elections', 'users', ['temp_admin_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('BIG_ADMIN', 'TEMP_ADMIN', 'ADMIN', 'VOTER', name='role'),
               existing_nullable=False)
    op.alter_column('voter_election_status', 'eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voter_election_status', 'eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('BIG_ADMIN', 'TEMP_ADMIN', 'ADMIN', 'VOTER', name='role'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.drop_index(op.f('ix_elections_secure_voting_token_hash'), table_name='elections')
    op.drop_index(op.f('ix_elections_secure_voting_token'), table_name='elections')
    op.drop_index(op.f('ix_elections_election_id'), table_name='elections')
    op.alter_column('elections', 'show_voter_names_in_results',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('elections', 'enable_step_5',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'enable_step_4',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'enable_step_3',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'enable_step_2',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('elections', 'voting_flow_mode',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'full'"))
    op.alter_column('elections', 'remote_voting_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('authentication_sessions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('authentication_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
